### ISSUE TITLE
Better types for `wrapper.vm` when the component is closed

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/vue-test-utils-next#972]
Since `2.0.0-rc.15`, we are now exposing `$.proxy` as `wrapper.vm` to simplify testing of `script setup` component,
allowing to test the following component:

```vue
<script setup lang="ts">
import { ref } from 'vue'
const count = ref(0)
</script>
```

with `expect(wrapper.vm.count).toBe(0)`, even if `count` is not exposed by the component (see PR #931 ).

This works, but for TS (`vue-tsc`), `wrapper.vm` does not have a `count` property, because `wrapper.vm` is typed as `ComponentPublicInstance`.

Ideally, we would like `wrapper.vm` type to reflect that it is actually not the component public instance, but the properties exposed to the template. Is there a way to infer that?

To reproduce, remove `"exclude": ["tests/expose.spec.ts"]` from `tsconfig.volar.json`, and run `yarn vue-tsc`. It fails with:

```
tests/expose.spec.ts:38:23 - error TS2339: Property 'count' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<Readonly<{} & {} & {}> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>; ... 10 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptions<...> | undefined): WatchStopHandle; } & ... 4 more ... & ComponentC...'.

38     expect(wrapper.vm.count).toBe(1)
```

**Comment by cexbrayat** [comment]
@pikax do you have an idea how we could solve that?

**Comment by pikax** [comment]
Currently that's not possible, I'm working on this PR https://github.com/vuejs/vue-next/pull/4465 to improve some types, I can have a look on how to also add that info there

**Comment by cexbrayat** [comment]
For anyone keeping up with this, @johnsoncodehk released vue-tsc@0.30.0 with a new option that improves the situation. See #1170

**Comment by felixzapata** [comment]
The explicit cast solution stops working with the last Vue release (3.2.45).

**Comment by cexbrayat** [comment]
@felixzapata are you using VTU v2.2.2 ? There was a breaking change in Vue v3.2.45, but the latest VTU release should work around it.

**Comment by felixzapata** [comment]
sorry, I forgot to mention that with VTU 2.2.2 also fails

**Comment by cexbrayat** [comment]
@felixzapata In that case, can you open an issue with a small repro using https://stackblitz.com/edit/vitest-dev-vitest-a961ap?file=package.json&initialPath=__vitest__ please? We'll take a look

**Comment by felixzapata** [comment]
I will try because we have some custom configuration and TypeScript typing rules.

```
System:
    OS: macOS 11.6.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 57.19 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Chrome Canary: 110.0.5417.0
    Firefox: 106.0.5
    Safari: 15.5
    Safari Technology Preview: 15.4
  npmPackages:
    @intlify/core-base: 9.2.2 => 9.2.2 
    @intlify/unplugin-vue-i18n: 0.7.3 => 0.7.3 
    @vitejs/plugin-vue: 3.2.0 => 3.2.0 
    @vue/eslint-config-typescript: 11.0.2 => 11.0.2 
    @vue/test-utils: 2.2.2 => 2.2.2 
    @vue/tsconfig: 0.1.3 => 0.1.3 
    vite: 3.2.3 => 3.2.3 
    vitest: 0.25.1 => 0.25.1 
    vue: 3.2.45 => 3.2.45 
    vue-i18n: 9.2.2 => 9.2.2 
    vue-loader: 17.0.1 => 17.0.1 
    vue-router: 4.1.6 => 4.1.6 
    vue-tsc: 1.0.9 => 1.0.9
```

I am reviewing the tests that are failing; all the ones we have using casting in order to spy methods.

**Comment by felixzapata** [comment]
[Is there a way to allow this mocking](https://stackblitz.com/edit/vitejs-vite-tzyzdy)? [Is similar to this one](https://stackblitz.com/edit/vitest-dev-vitest-pcp793?file=components%2FHello.vue) but the problem I think is because of _mount_ and because I am late setting the mock. I think it should be during the mounting process.

**Comment by cexbrayat** [comment]
@felixzapata It is not possible, as this is not possible in vanilla JS. See  https://github.com/vuejs/test-utils/issues/1798#issuecomment-1270223849 for more explanation.

**Comment by felixzapata** [comment]
> @felixzapata It is not possible, as this is not possible in vanilla JS. See [#1798 (comment)](https://github.com/vuejs/test-utils/issues/1798#issuecomment-1270223849) for more explanation.

ok, maybe I have some thoughts of something similar I did in the past regarding the framework/library.

**Comment by matthew-dean** [comment]
This may have been improved for vue-tsc, but it still fails with Volar AFAIK.

**Comment by cexbrayat** [comment]
@pm0u I don't think there are such issues upstream (but maybe there are, I haven't checked recently).
@pikax was working on a PR to improve the situation if I remember correctly, but I'm not sure of its status

**Comment by pm0u** [comment]
I saw that, however it looks like that has been untouched since 9/2021. The TS version referenced in the package json is a major version behind, so probably safe to say it is stale

**Comment by ulfgebhardt** [comment]
In component:
```
const slide = ref(0)

defineExpose({ slide })
```

In test:
```
it('has slide value 0', () => {
  expect(wrapper.vm.slide).toBe(0)
})
```

Not sure if proper solution, but solves the typing without any casts.

**Comment by cexbrayat** [comment]
@ulfgebhardt Thanks, but your solution is expected to work: this issue is for the cases where you _don't_ want to expose the variable.

**Comment by pikax** [comment]
This will require a few changes from https://github.com/vuejs/language-tools, since the SFC types are generated by it, I recommend created a cross issue over there.

**Comment by CreeTar** [comment]
Can't we just expose everything, when the component is mounted in test-utils? That would fix all issues.
